Refactor fill row
n1k0din/changelog_parser pull request #1
Opened 2020-06-15 04:46 UTC by n1k0din

2020-06-15 16:47 UTC, z00sts requested changes

2020-06-15 16:47 UTC, z00sts commented on changes.py
> +def formatted_dotted_next_num(num: int, pattern=IE_NAME_PATTERN) -> str:
```suggestion
def format_with_dots(num: int, pattern=IE_NAME_PATTERN) -> str:
```

Передавать извне уже увеличенное значение (чтобы уменьшить зону ответственности функции)

2020-06-15 16:47 UTC, z00sts commented on changes.py
> +            # 123 -> "Версия 1.2.4."
minor:  это (и выше) уже и так понятно из функции, которую применяешь

2020-06-15 16:47 UTC, z00sts commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
Непонятно, почему добавляется SORT_STEP

2020-06-15 16:47 UTC, z00sts commented on changes.py
> +            date = fix_date(common_logs[lb_type].date)
```suggestion
            date = format_date(common_logs[lb_type].date, 'dd.mm.yyyy')
```

2020-06-15 16:47 UTC, z00sts commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
Сложный интерфейс функции, разбить на две, либо дать говорящие kwargs

2020-06-16 03:31 UTC, n1k0din commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
а не +1? это про запас, вдруг потом надо будет что-то запихать между IE_SORT и IE_SORT + SORT_STEP. добавлять такое в комменты?

2020-06-16 03:50 UTC, n1k0din commented on changes.py
> +def formatted_dotted_next_num(num: int, pattern=IE_NAME_PATTERN) -> str:
Исправлю.

2020-06-16 03:50 UTC, n1k0din commented on changes.py
> +            # 123 -> "Версия 1.2.4."
Ок.

2020-06-16 03:57 UTC, z00sts commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
То есть это типа lag, чтобы потенциально что-то еще впихнуть?

2020-06-16 03:59 UTC, z00sts commented on changes.py
> +            date = fix_date(common_logs[lb_type].date)
Можно и так оставить, добавив docstring у функции fix_date

2020-06-16 04:00 UTC, z00sts requested changes

2020-06-16 04:00 UTC, z00sts commented on changes.py
> +            'IP_PROP23': replace_with_next_num(row['IP_PROP23'], prev_v),
Примеры, как работает функция лучше в её docstring перенести

2020-06-16 04:00 UTC, n1k0din commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
типа того, как z-index в css

2020-06-16 04:02 UTC, n1k0din commented on changes.py
> +            date = fix_date(common_logs[lb_type].date)
Ок

2020-06-16 04:02 UTC, n1k0din commented on changes.py
> +            'IP_PROP23': replace_with_next_num(row['IP_PROP23'], prev_v),
Ок

2020-06-16 04:03 UTC, z00sts commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
Частично понятней стало из камента к константе. Лучше вынести всё это (`int(row['IE_SORT']) + SORT_STEP`) в функцию и в описании к ней всё свести вместе

2020-06-16 04:03 UTC, n1k0din commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
Ок, что-то сделаю, перепризову

2020-06-16 04:56 UTC, z00sts commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
> говорящие kwargs

Скорее всего функция просто делает больше одной вещи, и это не поможет, нужно разбивать

2020-06-16 06:48 UTC, n1k0din commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
Вынес в отдельную функцию, прокомментировал, сделал шаг меньше.

2020-06-16 07:27 UTC, z00sts commented on changes.py
> +def fill_row(row, prev_v: int, date: str, full_log: t.List[str]):
Я бы переименовал `prev_v` в `version`

2020-06-16 07:33 UTC, z00sts commented on changes.py
> +            'IE_SORT': int(row['IE_SORT']) + SORT_STEP,
> Вынес в отдельную функцию, прокомментировал, сделал шаг меньше.

чет не увидел пока

2020-06-16 07:35 UTC, z00sts commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
upd: функция делает базовые вещи, решение - заинлайнить

2020-06-16 07:41 UTC, z00sts requested changes

2020-06-16 07:41 UTC, z00sts commented on changes.py
>      return '.'.join([d, m, y])
Вот букв тебе жалко)
`day, month, year = date.rstrip('.').split('.')` лучше как по мне.

И в конце можно не как коллекцию клеить тогда:
```
return f'{day}.{month}.{year}'
```

2020-06-16 07:48 UTC, n1k0din commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
вариант с kwargs
```suggestion
            full_log = get_full_log(type=lb_type, model=row['IC_GROUP1'],
            type_changelist=common_logs, model_changelist=spec_logs)
```

2020-06-16 07:50 UTC, n1k0din commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
вариант инлайн
```suggestion
            full_log = common_logs[lb_type].changelog.copy()
            model = row['IC_GROUP1']
            if model in spec_logs:
                full_log_2.extend(spec_logs[model].changelog)
```

2020-06-16 07:52 UTC, n1k0din commented on changes.py
> +def fill_row(row, prev_v: int, date: str, full_log: t.List[str]):
Согласен.

2020-06-16 07:54 UTC, n1k0din commented on changes.py
>      return '.'.join([d, m, y])
Ок!

2020-06-16 07:59 UTC, n1k0din commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
мне вариант с kwargs больше нра

2020-06-16 08:36 UTC, z00sts commented on changes.py
> +            full_log = get_full_log(lb_type, row['IC_GROUP1'], common_logs, spec_logs)
Пусть так

2020-06-16 08:41 UTC, z00sts approved these changes

2020-06-16 13:15 UTC, merged